- MediaBrowser.WebDashboard/dashboard-ui/css/site.css
When browser is exactly 1440px, unnecessary top margin added to first
right column, resulting in uneven column alignment. Positioning of right
column is also dependent on min-width 1440px in another location.
Changing to 1439px here resolves the conflict.
When the recent activity box is full with longer activities, the nav
buttons can get pushed ouut the bottom of the div because of the height
being set explicitly. Changing to min-height fixes the problem.
> Resolve 1440px dashboard layout conflict & keep notification nav buttons inside div

- MediaBrowser.Server.Implementations/Localization/JavaScript/javascript.json
- MediaBrowser.Server.Startup.Common/ApplicationHost.cs
- MediaBrowser.WebDashboard/dashboard-ui/scripts/dashboardpage.js
I've added ssl port information to the dashboard. I only added the label to the en_US file. I'll be happy to add it in any other file. 
First: is there an automated process for this that I don't know about? 
Second, if the language isn't English do I add the english label anyway or just leave the label out?
You are probably going to get a bunch of small pulls from me at this point. I get precious little time to do any "fun" work with a job, wife, and child. Let me know if they get too granular.
> Show ssl port on dashboard

- MediaBrowser.Model/System/SystemInfo.cs
- MediaBrowser.Server.Startup.Common/ApplicationHost.cs
The UseHttps property on the systeminfo class is used by the dashboard javascript. If this isn't the correct fix please let me know what is.
> Fix ssl port info on dashboard

- MediaBrowser.Dlna/PlayTo/PlayToController.cs
mediaInfo.Id is some long URL that ends with: Params=;uuid:8656a761-9b0c-868a-df35-d87147340fe8;88394665c46386ac96e5c3492b870ced;true;;;;;;;;;;;0;;;;;;"
I think item Id is what we want here. Is there a reason ItemId on PlaybackStartInfo is not of type Guid?
> Fix DLNA status reporting

- MediaBrowser.Api/Playback/BifService.cs
- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
BIF related fixes:
1) Give ffmpeg more time to create thumbnails, but periodically check to make sure the process did not hang.
2) Reverse Endianness for integer values in the index.bif file.
> Bluebull32 patch 1

- MediaBrowser.Controller/Entities/TV/Series.cs
The TvdbSeasonImageProvider was running before the TvdbSeasonImageProvider. This caused the seriesid be null on the series. (This is apparently populated as part of the metadata refresh on the series.) Moving that scan before the seasons seems to fix the problem.
See the following code from TvdbSeriesImageProvider
var seriesId = series != null ? series.GetProviderId(MetadataProviders.Tvdb) : null;
if (!string.IsNullOrEmpty(seriesId) && season.IndexNumber.HasValue)
> Fix season images not showing up when Emby starts.

- MediaBrowser.Server.Implementations/UserViews/DynamicImageProvider.cs
DynamicImageProvider:CreateImageAsync was not marked as async. When returning null the await BaseDynamicImageProvider:FetchToFileInternal would throw a null reference exception. An alternative solution would be to wrap the null return in Task.FromResult.
Object reference not set to an instance of an object.
System.NullReferenceException
at MediaBrowser.Server.Implementations.Photos.BaseDynamicImageProvider`1.<FetchToFileInternal>d__c.MoveNext() in c:\MediaBrowser\MediaBrowser.Server.Implementations\Photos\BaseDynamicImageProvider.cs:line 79
> Fix null reference exception when awaiting null.

- MediaBrowser.WebDashboard/dashboard-ui/css/site.css
Rewrote http fonts.gstatic.com to https to get rid of warnings in Firefox and Chrome.
> Unsafe connection to http is prevented when using https.

- MediaBrowser.MediaEncoding/Subtitles/SrtParser.cs
- MediaBrowser.Tests/MediaEncoding/Subtitles/TestSubtitles/unit.srt
When failing to parse srt subtitles with ssa tags, the server will leave an http request in an opened state, never returning. At least until the request times out. _No errors are present in the log_ which is more worrisome, but the server is still functional after the user cancels their srt request (probably still functional during as well). This should probably be handled more gracefully, but left out of this merge.
The tag in question was a color change: `\c&H000000&`. I've changed the tag regex to handle more ssa tags, including color and alpha tags. The only regression would be brackets within brackets, but I don't see this as a possibility based on my quick glance of the spec.
> Add support for more ssa tags in SrtParser

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
Resubmitted for the dev branch.
The name of the Musicbrainz tags differs between ID3 tags and Vorbis comments, meaning ffmpeg reports diffrent names as well.
I found this beeing a problem as MusicBrainz Picard always write Vorbis comments to flac files. See https://picard.musicbrainz.org/docs/mappings/ for mappings used my MusicBrainz Picard.
> MusicBrainz ids as Vorbis Comments

- MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs
Moving pullreq #1181 over to dev branch
ffprobe output parsing implementation only works with windows style line endings.
When running the library scan on a linux machine, ffprobe uses only newlines so the regex didn't actually split the ffprobe output.
The subsequent linq code that splits each line on '=' and calls to ToDictionary() would end up throwing an ArgumentException due to duplicate keys.
> Fix ffprobe keyframe detection on linux

- MediaBrowser.Server.Implementations/FileOrganization/TvFolderOrganizer.cs
During Auto-Organize, Emby should maintain a list of folders which were
processed successfully. Only these folders should be used with the
DeleteLeftOverFiles and DeleteEmptyFolders functions.
> Auto-Organize: Perform leftover-file and empty-folder deletion in processed folders only (targeting dev branch)

- MediaBrowser.Providers/Manager/ProviderManager.cs
Previously, when a remote search (without provider restriction) was
executed, the search used results from the first provider that returned
at least a single result only. Other providers were ignored.
This commit changes the behaviour in a way that all available providers
are queried until a certain number of search results has been collected.
The number is hardcoded to 10 (like it was before), but could be
parametrized in the future.
> Remote-Search: Allow result aggregation of multiple providers

- MediaBrowser.Server.Implementations/FileOrganization/EpisodeFileOrganizer.cs
This replaces pull request #1189
Especially with Multi-Episodes, the EpisodeTitle can become quite long,
since all comprised titles get concatenated into it.
By default, the EpisodeTitle is included in the single and multi-episode
naming patterns and this in turn can quickly lead to a
PathTooLongException.
This fix tries to keep as much as possible from the title string while
keeping the final path within the allowed limit.
> Auto-Organize: Fix PathTooLongException due to long EpisodeTitle

- MediaBrowser.Server.Implementations/FileOrganization/TvFolderOrganizer.cs
PathTooLongException can not only occur with long destination paths but
also with too long file names of files contained in a watch folder.
Previously this condition caused the auto-organize task to break.
With this change, we still log the exception, but auto-organize
processing will continue to handle all other files.
> Auto-Organize: PathTooLongException on source file should not break auto-organize task

- MediaBrowser.WebDashboard/dashboard-ui/scripts/autoorganizelog.js
- MediaBrowser.WebDashboard/dashboard-ui/strings/javascript/en-US.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/javascript/javascript.json
This is a resubmit of pull request #1197 against the dev branch:
When an exception occured on the server, the organize dialog or the confirm dialog were displayed eternally and not indication of failure was presented to the user
> Auto-Organize: Display errors in client on server exceptions

- MediaBrowser.Providers/Movies/MovieDbSearch.cs
- MediaBrowser.Providers/Omdb/OmdbItemProvider.cs
- MediaBrowser.Providers/TV/TvdbSeriesProvider.cs
* OmdbProvider: The result often contains strings like '2010-' or
'2010-2012'. I fixed the parsing to use the first 4 digits only in these
cases
* TheMovieDb: While the search method did send appropriate queries for
different search types, it didn't differentiate for deserialization of
results. I fixed this at least for the TvResults, in order to get the
'first_air_date' property parsed.
*  TheTvdb: The parsing of the 'FirstAired' node was missing here as
well (for search results)
> Remote-Search: Fixed providers to return year information when searching for series

- MediaBrowser.WebDashboard/dashboard-ui/scripts/livetvcomponents.js
Because of JS hoisting rules, a stale value was being used for image urls. This remedies that.
Here is an example of the bug in action:
> Fix issue where shows without icons would use the last icon that was displayed

- MediaBrowser.Model/Configuration/ServerConfiguration.cs
- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- MediaBrowser.Providers/Omdb/OmdbItemProvider.cs
- MediaBrowser.Providers/TV/OmdbEpisodeProvider.cs
- MediaBrowser.Server.Implementations/FileOrganization/EpisodeFileOrganizer.cs
- MediaBrowser.Server.Startup.Common/ApplicationHost.cs
- MediaBrowser.Server.Startup.Common/MediaBrowser.Server.Startup.Common.csproj
- MediaBrowser.Server.Startup.Common/Migrations/OmdbEpisodeProviderMigration.cs
This new episode provider implementation does not bulk-download or cache
episode data. It is only meant to be a backup source for situations
where media is not recognized by that default provider.
> Extended OmdbItemProvider to support series episodes

- MediaBrowser.Providers/MediaBrowser.Providers.csproj
- MediaBrowser.Providers/TV/MovieDbEpisodeImageProvider.cs
- MediaBrowser.Providers/TV/MovieDbEpisodeProvider.cs
- MediaBrowser.Providers/TV/MovieDbProviderBase.cs
- MediaBrowser.Server.Startup.Common/ApplicationHost.cs
- MediaBrowser.Server.Startup.Common/MediaBrowser.Server.Startup.Common.csproj
- MediaBrowser.Server.Startup.Common/Migrations/MovieDbEpisodeProviderMigration.cs
Most of the required logic already existed in MovieDbEpisodeImageProvider.
In order to avoid duplicated code, I have moved all common code to a new base class "MovieDbProviderBase" from which MovieDbEpisodeProvider and 
MovieDbEpisodeImageProvider are inheriting now.
> Created new Metadata provider for TheMovieDB: MovieDbEpisodeProvider

- MediaBrowser.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
Use the correct resolution (960x548) for the internet540 profile.
Actually advertise the internet540 profile.
Remove the obsolete internet720 profile, which is no longer supported on current firmware.
> fix transcoding profiles for HDHomeRun Extend (dev)

- MediaBrowser.Model/LiveTv/LiveTvOptions.cs
- MediaBrowser.Server.Implementations/LiveTv/TunerHosts/HdHomerun/HdHomerunHost.cs
- MediaBrowser.WebDashboard/dashboard-ui/livetvtunerprovider-hdhomerun.html
- MediaBrowser.WebDashboard/dashboard-ui/scripts/livetvtunerprovider-hdhomerun.js
- MediaBrowser.WebDashboard/dashboard-ui/strings/en-US.json
This change adds a checkbox on the tuner configuration page that allows the hardware transcoding functionality of the HDHomeRun Extend (HDTC-2US) to be disabled.
> allow disabling of hardware transcoding on HDTC-2US (dev)

- MediaBrowser.Providers/BoxSets/MovieDbBoxSetProvider.cs
- MediaBrowser.Providers/Movies/FanArtMovieUpdatesPostScanTask.cs
- MediaBrowser.Providers/Movies/FanartMovieImageProvider.cs
- MediaBrowser.Providers/Movies/GenericMovieDbInfo.cs
- MediaBrowser.Providers/Movies/MovieDbProvider.cs
- MediaBrowser.Providers/Movies/MovieDbSearch.cs
- MediaBrowser.Providers/Movies/MovieExternalIds.cs
- MediaBrowser.Providers/Movies/MovieUpdatesPrescanTask.cs
- MediaBrowser.Providers/Music/FanArtArtistProvider.cs
- MediaBrowser.Providers/Music/FanArtUpdatesPostScanTask.cs
- MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs
- MediaBrowser.Providers/Music/MusicBrainzArtistProvider.cs
- MediaBrowser.Providers/Music/MusicExternalIds.cs
- MediaBrowser.Providers/Omdb/OmdbImageProvider.cs
- MediaBrowser.Providers/Omdb/OmdbItemProvider.cs
- MediaBrowser.Providers/Omdb/OmdbProvider.cs
- MediaBrowser.Providers/People/MovieDbPersonProvider.cs
- MediaBrowser.Providers/TV/FanArt/FanArtTvUpdatesPostScanTask.cs
- MediaBrowser.Providers/TV/FanArt/FanartSeriesProvider.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbProviderBase.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeasonProvider.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs
- MediaBrowser.Providers/TV/TheTVDB/TvdbPrescanTask.cs
- MediaBrowser.Providers/TV/TheTVDB/TvdbSeriesProvider.cs
- MediaBrowser.Providers/TV/TvExternalIds.cs
- OpenSubtitlesHandler/Utilities.cs
The following domains are not HTTPS enabled:
www.imdb.com
www.theaudiodb.com
tvlistings.zap2it.com
bot.whatismyipaddress.com
May have missed a few, but at least all Providers are covered.
> Use HTTPS for API requests

- MediaBrowser.Providers/BoxSets/MovieDbBoxSetProvider.cs
With this change I propose that english metadata from collection (fallback situation) occurs when a collection **NAME **is missing, instead of **OVERVIEW **(description).
This means a translated collection that has the vital information such as name will be sufficient to be used... not forcing Emby to download english data (with the non-translated title and overview) just because the translated version has an empty overview.
I took a while to understand why some of my collections weren't downloading their translated versions from provider. I traced the problem to this... the ones who had overview were pulled in, the ones who hadn't Emby used the fallback (easily seen in the logs).
> Collection meta-fetch fallback condition update

- MediaBrowser.Controller/Entities/TV/Episode.cs
Minimal changes to support linking remote trailers [eg. YouTube] to episodes, to support manual editing or future meta providers [eg. tvmaze one the api includes this info]
> Remote Trailers support at episode Level

- MediaBrowser.Providers/Omdb/OmdbProvider.cs
Avoid malformed json because some day jsonserializer may change its behaviour or be replaced by something less tolerant...
> OmdbProvider: Fix for empty json fields

- MediaBrowser.Providers/Omdb/OmdbImageProvider.cs
- MediaBrowser.Providers/Omdb/OmdbItemProvider.cs
- MediaBrowser.Providers/Omdb/OmdbProvider.cs
- MediaBrowser.Providers/TV/Omdb/OmdbEpisodeProvider.cs
This commit implements caching for the OMDB provider.
Caching is performed on each single item at  this time.
It is expected that a multi-episode API method will become available soon.
This commit also adds a check for image availability to the OmdbImageProvider to prevent empty primary images from being auto-selected for library items.
Last, this commit enables OmdbImageProvider for series episodes
> Result caching and image existance check for OMDB

- MediaBrowser.WebDashboard/dashboard-ui/scripts/autoorganizelog.js
- MediaBrowser.WebDashboard/dashboard-ui/scripts/autoorganizesmart.js
- MediaBrowser.WebDashboard/dashboard-ui/scripts/autoorganizetv.js
- MediaBrowser.WebDashboard/dashboard-ui/scripts/dashboardhosting.js
- MediaBrowser.WebDashboard/dashboard-ui/scripts/dlnaprofile.js
- MediaBrowser.WebDashboard/dashboard-ui/scripts/site.js
This commit adds a new dashboard method for generic handling of api errors.
It also changes local implementations to use the dashboard method.
This allows global control of error presentation (e.g. to switch to toast notifications if desired).
> Dashboard method for response error handling

- MediaBrowser.ServerApplication/App.config
Disables the FIPS Validation Check to allow the MediaBrowser Server Application to run on a Trusted Platform enabled computer running Windows 10. Important information regarding the addition can be found on MSDN: https://msdn.microsoft.com/en-us/library/hh202806(v=vs.110).aspx
While in our discussions with Microsoft Government and Enterprise Support it has been indicated that it's best practice to move to a FIPS validated encryption method (please see MSDN: https://msdn.microsoft.com/en-us/library/0ss79b2x(v=vs.110).aspx to determine an appropriate algorithm), this patch will at minimum allow the application to run by specifying whether to enforce a computer configuration requirement that cryptographic algorithms must comply with the Federal Information Processing Standards or "FIPS." …
> Disable FIPS Validation Check in App.config

- MediaBrowser.WebDashboard/dashboard-ui/channelitems.html
This commit removes the data-contextname attribute which was leading to incorrect view titles being set.
The (correct) title is always set from script anyway...
> Fix incorrect library title being set on back/forward browser navigation

- MediaBrowser.Providers/Omdb/OmdbProvider.cs
- MediaBrowser.Providers/TV/Omdb/OmdbEpisodeProvider.cs
Finally: No more per-episode requests with OMDB. Episode data is now retrieved and cached for each season.
> OMDB Episode Provider: Use new full season API for retrieval and caching

- MediaBrowser.Server.Implementations/Channels/ChannelManager.cs
A channel plugin must be able to present items in just the order in which it provides items to the host.
This is the "Default" sort order option. In this case, Emby must not perform sorting by "Name".
Sorting by "Name" is a different option. A user can set this or the channel can set this. But if the "Default" option is selected, items must not be sorted by "SortName"
> Channel item sort must not default to name sorting when all sort fields are cleared

- MediaBrowser.WebDashboard/dashboard-ui/css/librarybrowser.css
This would be one way to preserve line breaks in overview descriptions.
Another method would be to insert BR tags during acquisition of the description data...
> Preserve line breaks in item overview

- MediaBrowser.Api/Playback/BaseStreamingService.cs
- MediaBrowser.MediaEncoding/Encoder/BaseEncoder.cs
- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
- MediaBrowser.MediaEncoding/Encoder/EncodingJobFactory.cs
- MediaBrowser.WebDashboard/dashboard-ui/encodingsettings.html
This adds support for nvenc to the UI, I've done some limited testing and so far so go, but I marked it as "experimental" in the UI since I wanted people to be sure to understand.
Basically renaming libnvenc to h264_nvenc and changing the parameters from high-performance to llhq (low latency high quality) as high-performance is no longer valid.
Going forward I think that more optimizations for nvenc can be made, but seemed like the place to start.
> Fixes for nvenc support marked as experimental

- MediaBrowser.Api/Playback/BaseStreamingService.cs
When using h264_nvenc, the preset is set to "high-performance" which isn't a valid preset according to the nvenc encoder. For now it's set to default to get a working version.
> Changed to a valid preset for h264_nvenc

- MediaBrowser.Api/Dlna/DlnaService.cs
Currently, dlna update profile dosen't work properly due to `Profile is missing Id`
**how to reproduct bug?**
1. prepare emby version 3.0.5986 and install it on linux
(I suspect this bug affect all version of emby, but mine is 3.0.5986)
2. enter emby manager -> DLNA -> Profiles -> Press New button to create custom dlna profile
3. press save button to save custom profile
4. click custom profile which created by previous step
5. change any option and save
6. it raises error `Profile is missing Id`
[https://github.com/MediaBrowser/Emby/blob/923ab2ab3543dc36ddf291775ecd29c1836fb379/MediaBrowser.Dlna/DlnaManager.cs#L453](https://github.com/MediaBrowser/Emby/blob/923ab2ab3543dc36ddf291775ecd29c1836fb379/MediaBrowser.Dlna/DlnaManager.cs#L453) …
> fix dlna update profile

- MediaBrowser.Server.Implementations/Connect/ConnectManager.cs
That Uri constructor is throwing very often at my site, and avoiding exceptions is usually better than catching, of course.
> Avoid frequent Exception

- MediaBrowser.Api/Playback/Progressive/BaseProgressiveStreamingService.cs
We were calculating bits, but we need this in bytes3
> Fix incorrect calculation of content length

- MediaBrowser.Server.Implementations/FileOrganization/EpisodeFileOrganizer.cs
- MediaBrowser.Server.Implementations/FileOrganization/FileOrganizationService.cs
- MediaBrowser.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs
**Note: This is an alternate approach to PR #2058**
Previously some methods were just returning null or empty values in case
of encountered errors; as a consequence, the actual reason for failure
was never written to the auto-organize log.
Instead, only a generic message like "Unable to sort xxx because target
path could not be determined." was displayed.
After this change, the actual reason for failure will be saved to the
auto-organize log or displayed in the UI (when completing the organize
dialog).
This information is very important for the user. Examples are "No
permission", "Target folder not available", "Disk full", etc..
> EpisodeFileOrganizer: Improve error handling (alternate approach)

- MediaBrowser.Server.Implementations/Sync/SyncedMediaSourceProvider.cs
The item.Id is valid for this purpose because it provides a unique identifier for the synced file.
Background: A persistent ETag value enables range-based streaming and seeking of static files being served via http.
> Provide (unique) ETag value for synced media sources

- MediaBrowser.Server.Implementations/Udp/UdpServer.cs
UDP response should be of higher priority than the rarely needed Loopback exemption
> send udp response first

- MediaBrowser.Api/Playback/BaseStreamingService.cs
- MediaBrowser.MediaEncoding/Encoder/BaseEncoder.cs
Fix the broken ffmpeg filter for graphical subtitles in vaapi transcoding mode and change the vaapi hwaccel_output_format to yuv420p. Thus, ffmpeg copies decoded frames to normal memory to support general ffmpeg filter graphs.
> fix graphical subtitle transcoding with vaapi

- MediaBrowser.Api/Playback/BaseStreamingService.cs
- MediaBrowser.MediaEncoding/Encoder/BaseEncoder.cs
Copy frames to main memory only when graphical subs are transcoded. Thus, the optimal vaapi transcoding performance is restored in most cases (regression fix).
> vaapi: copy decoded frames to main memory only when necessary

- Emby.Server.Implementations/Connect/ConnectEntryPoint.cs
In an effort to reduce unnecessary disk IO so that Synology products are able to hibernate the disk drives (or for the disk drives to not be woken up by disk IO), this PR updates the WAN IP detection code in `ConnectEntryPoint` to not write out the WAN IP address to disk if it has not changed. The WAN IP detection still happens hourly as before, the only difference is that the **wan.dat** file is not updated unnecessarily if the IP address has not changed since the last check.
In the existing code, `ConnectEntryPoint` also calls `ConnectManager.OnWanAddressResolved` hourly when the WAN IP is resolved. That ultimately causes further disk IO to the **connect.txt** file due to writing out of `ConnectData`. This further writing to **connnect.txt** is however not addressed in the single commit …
> Do not update wan.dat if WAN IP has not changed

- MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs
I have a plugin that implements an IExternalId. The BaseNfoSaver saves this ID but the BaseNfoParser does not read the saved ID.
e.g. this is written by BaseNfoSaver but BaseNfoParser ignores the mymovieid element
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<movie>
<title>My Movie Title</title>
<mymovieid>movie654321</mymovieid>
......
</movie>
```
This PR adds the code from BaseItemXmlParser that handles processing user defined IExternalIds to BaseNfoParser.
> Update BaseNfoParser to handle user defined IExternalIds

- MediaBrowser.WebDashboard/dashboard-ui/manifest.json
The `start_url` was wrong in the manifest.json, causing a 404 error on Android when adding Emby to home screen.
> fix wrong start url in manifest.json

- MediaBrowser.XbmcMetadata/Savers/AlbumNfoSaver.cs
- MediaBrowser.XbmcMetadata/Savers/ArtistNfoSaver.cs
- MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs
- MediaBrowser.XbmcMetadata/Savers/EpisodeNfoSaver.cs
- MediaBrowser.XbmcMetadata/Savers/MovieNfoSaver.cs
- MediaBrowser.XbmcMetadata/Savers/SeasonNfoSaver.cs
- MediaBrowser.XbmcMetadata/Savers/SeriesNfoSaver.cs
This PR fixes the custom IExternalIds defined by my plugin being written to the .nfo file multiple times after the first save. The custom IExternalIds are added to the list returned by the TagsUsed method
When the .nfo is saved for the first time it contains the external id.
e.g.
```xml
<movie>
...
<myexternalid>1234</myexternalid>
...
<fileinfo>
...
</fileinfo>
</movie>
```
If the file is saved 3 times it ends up looking like this:
```xml
<movie>
...
<
<myexternalid>1234</myexternalid>
...
<fileinfo>
...
</fileinfo>
<myexternalid>1234</myexternalid>
<myexternalid>1234</myexternalid>
<myexternalid>1234</myexternalid>
</movie>
```
> Update NfoSavers so they don't duplicate user defined IExternalIds

- MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs
This hould be added for letting emby recognize this hw-decoders and encoders. This in addition to  #2506 and on the dev branch as wished.
>  Add hevc hw-decoders and encoders to var required

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Without those little changes, rtsp live tv streams get corrupted even when stream copying, but also with transcoding.
It's already really bad for sd streams, but hd streams are just unwatchable. The whole picture consists of green blocks.
Btw. this problem isn't new. It was already discussed in many posts at the time the Argus TV plugin was still alive.
These changes have the potential to fix it there also.
> Improve playback of RTSP streams

- .gitignore
- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
This if clause should enable deinterlacing while transcoding with vaapi. This is very useful if Live-TV is used. At the moment the channels are just streamed interlaced if vaapi is enabled.
> Enable deinterlacing for transcoding with vaapi

- MediaBrowser.Providers/Manager/ProviderManager.cs
Set the contentType to image/png when tvheadend doesn't provide any contentType.
> + workaround for tvheadend channel icons

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Sorry, lets try this again
Here is an fix to have intel quick sync to respect the hardware encoding settings for h264
https://emby.media/community/index.php?/topic/56730-emby-not-respecting-h264-encoding-preset-setting-on-hardware-encoding-for-intel-quick-sync/
Let me know if i need to change anything
> Fix for Intel Quicksync to respect h.264 encoding settings

- MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
This lets nvenc hardware encoding respect the options selected for encoding.
Discussion here https://emby.media/community/index.php?/topic/57528-testing-nvenc-for-encoding-options
> nvenc to respect hardware encoding.
