- MediaBrowser.Server.Implementations/Library/PathExtensions.cs
- MediaBrowser.Server.Implementations/Library/Resolvers/Movies/MovieResolver.cs
> Add imdbid detection from media file

- MediaBrowser.Controller/IServerApplicationHost.cs
- MediaBrowser.Controller/Net/IHttpServer.cs
- MediaBrowser.Controller/Net/IServerManager.cs
- MediaBrowser.Model/Configuration/ServerConfiguration.cs
- MediaBrowser.Model/System/SystemInfo.cs
- MediaBrowser.Server.Implementations/HttpServer/HttpListenerHost.cs
- MediaBrowser.Server.Implementations/HttpServer/SocketSharp/WebSocketSharpListener.cs
- MediaBrowser.Server.Implementations/Localization/Server/server.json
- MediaBrowser.Server.Implementations/ServerManager/ServerManager.cs
- MediaBrowser.Server.Startup.Common/ApplicationHost.cs
- MediaBrowser.WebDashboard/dashboard-ui/dashboardgeneral.html
- MediaBrowser.WebDashboard/dashboard-ui/scripts/dashboardgeneral.js
Can't change pull request target branch apparently. (Or I couldn't figure out how.)
This has been updated to allow certificate to be configurable, although it's hard coded right now. Will update the UI once the internals have been decided on\approved.
Whats the UDP port used for?
> Ssl in mediabrowser against new listener.

- MediaBrowser.Server.Implementations/Connect/ConnectManager.cs
If ssl is configured, assume public port point to https port. (Why else would you set it up?)
> If using https make remote url reflect that.

- MediaBrowser.Dlna/Ssdp/SsdpHandler.cs
According to the spec: http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0-20080424.pdf device responses to search should be delayed a random duration between 0 and the delay, not equal to the delay.
This was causing a bunch of my clients to time out attempting to connect to the server,
> Don't sleep too long responding to dlna search requests.

- MediaBrowser.Common.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
- MediaBrowser.Common.Implementations/ScheduledTasks/TaskManager.cs
- MediaBrowser.Common/MediaBrowser.Common.csproj
- MediaBrowser.Common/ScheduledTasks/DailyTrigger.cs
- MediaBrowser.Common/ScheduledTasks/ITaskManager.cs
- MediaBrowser.Common/ScheduledTasks/ITaskTrigger.cs
- MediaBrowser.Common/ScheduledTasks/IntervalTrigger.cs
- MediaBrowser.Common/ScheduledTasks/StartupTrigger.cs
- MediaBrowser.Common/ScheduledTasks/SystemEventTrigger.cs
- MediaBrowser.Common/ScheduledTasks/TaskExecutionOptions.cs
- MediaBrowser.Common/ScheduledTasks/WeeklyTrigger.cs
This is a little more palatable by using default params on the interface. (Could use overloads as well, personal choice.)
> Prototype 3 of max task length for scheduled tasks.

- Docker/Dockerfile
> Expose HTTPS

- MediaBrowser.Api/EnvironmentService.cs
- MediaBrowser.Controller/Providers/DirectoryService.cs
> Handle symlinks in library folders

- MediaBrowser.Dlna/Ssdp/SsdpHandler.cs
> Make sure to configure socket with Broadcast-options

- MediaBrowser.Providers/Omdb/OmdbItemProvider.cs
In my configuration, the Omdb provider is the first in the list for
movie metadata. This was the default at the time I installed MB and I
never changed that (don't know what the current defaults are for a new
installation).
When I use the identify command for movies in the metadata editor, I
always get a single result only. This is due to the fact that the Omdb
provider used the title API with "t=moviename", while there is also a
search api with "s=moviename" which will return multiple results.
This commit modifies the OmdbItemProvider to use the search API variant
and enable returning multiple results
> OmdbItemProvider: Use search instead of title API

- MediaBrowser.Providers/Manager/ProviderManager.cs
This is a revision to pull request #1205 which tries to avoid returning
duplicate results from multiple providers.
Duplicates are eliminated in two stages:
* Check for duplicate provider ids
* In case of movies and series: Also remove duplicates by title/year
combination
The second stage is required because search results of themoviedb and
thetvdb  do not contain external ids and performing separate queries for
each individual result would be too expensive. This is not an ideal
solution, but Name/Year is anyway just exactly that information which is
presented to the client in the results - apart from the image, of
course.
Images are only aggregated on matching provider ids, though. To allow
image aggregation over all search results, the breaking condition once
the result list is full has …
> Remote-Search:  Suppress duplicates when agregating results from multiple providers

- MediaBrowser.Server.Implementations/FileOrganization/EpisodeFileOrganizer.cs
Sometimes TheTVDb does not have episode. This caused an exception in
EpisodeFileOrganizer
> Fix exception when episode title is null

- MediaBrowser.Dlna/Profiles/KodiProfile.cs
- MediaBrowser.Dlna/Profiles/Xml/Kodi.xml
~~EDIT: I forgot to update `KodiProfile.cs`. Let me add those edits as well.~~
EDIT2: all is well, please merge
> Add support for embedded subtitles in Kodi's DLNA profile

- MediaBrowser.Server.Implementations/Configuration/ServerConfigurationManager.cs
Emby can only use certificates in PFX format which include a private key, and where the private key is not protected with a password.
Checking these conditions early helps to avoid misconfigurations and reduce troubleshooting time...
> ServerConfigurationManager: Check if a specified SSL certificate can be used when configuration is saved

- MediaBrowser.Api/Reports/ReportsService.cs
- MediaBrowser.Api/UserLibrary/BaseItemsRequest.cs
- MediaBrowser.Api/UserLibrary/ItemsService.cs
- MediaBrowser.Model/Querying/ItemFilter.cs
- MediaBrowser.Server.Implementations/IO/LibraryMonitor.cs
- MediaBrowser.WebDashboard/dashboard-ui/reports.html
- MediaBrowser.WebDashboard/dashboard-ui/scripts/reports.js
Add Not Favorite to filters
Fix export to include all items
> Report Fixes

- README.md
I think it looks more proper if this initialism is capitalized.
> Capitalize API

- MediaBrowser.WebDashboard/MediaBrowser.WebDashboard.csproj
- MediaBrowser.WebDashboard/dashboard-ui/autoorganizelog.html
- MediaBrowser.WebDashboard/dashboard-ui/bower_components/emby-apiclient/apiclient.js
- MediaBrowser.WebDashboard/dashboard-ui/components/fileorganizer/fileorganizer.js
- MediaBrowser.WebDashboard/dashboard-ui/components/fileorganizer/fileorganizer.template.html
- MediaBrowser.WebDashboard/dashboard-ui/scripts/autoorganizelog.js
- MediaBrowser.WebDashboard/dashboard-ui/strings/javascript/en-US.json
- MediaBrowser.WebDashboard/dashboard-ui/strings/javascript/javascript.json
This commit separates the auto-organize dialog into a component.
Further, this commit includes all of my UI changes, even for "new series creation" and "movie organization" features, although the backend implementation of those features is still missing.
> Organizedialogascomponent

- MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs
- MediaBrowser.Model/Entities/PersonType.cs
you know I don't think GitHub is my friend. 
I am trying
> music lyricist, writer

- MediaBrowser.Server.Implementations/LiveTv/TunerHosts/M3uParser.cs
Improvements to the parser and recognizes satip format.
> M3u Parser Improvements

- MediaBrowser.Providers/TV/TheMovieDb/MovieDbEpisodeProvider.cs
Auto-Organize is calling GetSearchResults to resolve episode titles.
Implementing GetSearchResults enables use of this provider from auto-organize.
> MovieDbEpisodeProvider: Implement GetSearchResults to allow usage from auto-organize

- MediaBrowser.Api/Playback/BaseStreamingService.cs
One more time.
A yes no or maybe would be nice
> qsv encode liveTV

- MediaBrowser.Controller/Entities/TV/Series.cs
This commit can significantly improe library scan times!
(in my case from 15minutes to 50s)
This improves the following situation:
When a user has a series in his library with lots of episodes (like
thousands), the metadata for ALL series episodes was refreshed during
each library scan. This resulted in very long scan times, even when
using the provider's cached data.
This fix skips metadata refresh for episodes that are NOT present in the
local library and are having an airdate older than 30days (no more
changes likely to occur) during library scans.
But these skipped items would still be refreshed during a full metadata
refresh.
I believe this is an acceptable balance between performance and
accuracy.
> Restrict metadata refresh of missing/virtual episodes

- MediaBrowser.Providers/Omdb/OmdbProvider.cs
omdbapi.com likes to return "N/A" for fields whithout content.
This can cause problems when metadata results are merged: During merge, the "N/A" value is used, even if other providers (of lower priority) had better data.
The previous implementation had handled this problem for certain fields only.
This commit solves the problem for all fields in a generic way..
> OmdbProvider: Fix for data fields containing "N/A"

- MediaBrowser.Providers/Omdb/OmdbImageProvider.cs
- MediaBrowser.Providers/Omdb/OmdbProvider.cs
> OmdbProvider instantiation

- MediaBrowser.Providers/TV/TheMovieDb/MovieDbEpisodeProvider.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbProviderBase.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeasonProvider.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs
- MovieDbSeasonProvider: Don't fill name from search info
- MovieDbSeriesProvider and MovieDbEpisodeProvider: Add support for trailers
> TheMovieDB Changes

- MediaBrowser.Server.Implementations/LiveTv/Listings/XmlTvListingsProvider.cs
Luke, this will also require a refresh of the XmlTv component as I've updated that also to handle TimeZone offsets
> IsSeries driven by Episode data

- MediaBrowser.Server.Implementations/Channels/ChannelManager.cs
> At least update names of container folders (originating from a Channel)

- MediaBrowser.Providers/BoxSets/MovieDbBoxSetImageProvider.cs
- MediaBrowser.Providers/Movies/MovieDbImageProvider.cs
- MediaBrowser.Providers/Movies/MovieDbProvider.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbEpisodeImageProvider.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbProviderBase.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesImageProvider.cs
> Adjust language for image results from TMDB when querying complex language codes (> 2 chars, qualified by country)

- MediaBrowser.Providers/Omdb/OmdbItemProvider.cs
- MediaBrowser.Providers/Omdb/OmdbProvider.cs
- MediaBrowser.Providers/TV/Omdb/OmdbEpisodeProvider.cs
- Improved parsing of production year (cases like '2001-2003')
- Parse writer field as person
- Parse director field as person
- Parse actors fields as persons
> Omdb Improvements

- MediaBrowser.WebDashboard/dashboard-ui/components/metadataeditor/metadataeditor.js
As suggested in #1811
I tested a standard workflow, but I couldn't do too much other testing. Let me know if there is anything else I should change or checkout
> Remove Jquery from metadataeditor.js

- MediaBrowser.Tests/ConsistencyTests/Resources/SampleTransformed.htm
- MediaBrowser.Tests/ConsistencyTests/Resources/StringCheck.xslt
- MediaBrowser.Tests/ConsistencyTests/Resources/StringCheckSample.xml
- MediaBrowser.Tests/ConsistencyTests/StringUsageReporter.cs
- MediaBrowser.Tests/ConsistencyTests/TextIndexing/IndexBuilder.cs
- MediaBrowser.Tests/ConsistencyTests/TextIndexing/WordIndex.cs
- MediaBrowser.Tests/ConsistencyTests/TextIndexing/WordOccurrence.cs
- MediaBrowser.Tests/ConsistencyTests/TextIndexing/WordOccurrences.cs
- MediaBrowser.Tests/MediaBrowser.Tests.csproj
StringUsageReporter reports usages of localization strings in the web
application and can also list all unused strings
> Add StringUsageReporter

- MediaBrowser.ServerApplication/MainStartup.cs
- MediaBrowser.ServerApplication/ServerNotifyIcon.cs
Also implemented the recommended pattern for IDisposable.
> Fix: Emby notification icon remained visible after shutdown

- MediaBrowser.Server.Implementations/Library/LibraryManager.cs
Fixes situations where the filename is something like "-------".
> Fix IndexOutOfRangeException

- MediaBrowser.WebDashboard/dashboard-ui/dlnaprofile.html
This option does not seem to be used anywhere
> Hide unused DLNA option

- MediaBrowser.WebDashboard/dashboard-ui/reports.html
Fix indentation of status block
Allow scroll bar for filters pane
> allow scroll bar on filters pane

- MediaBrowser.Common.Implementations/ScheduledTasks/ScheduledTaskWorker.cs
- MediaBrowser.Server.Implementations/FileOrganization/FileOrganizationNotifier.cs
- MediaBrowser.WebDashboard/dashboard-ui/dashboard/autoorganizelog.js
Also removed unused method in ScheduledTaskWorker
> AutoorganizeLog: Fixed error when log empty; re-introduced full reload on task completion

- MediaBrowser.Model.net35/MediaBrowser.Model.net35.csproj
The master branch was broken on a fresh clone, I renamed the wrong path to the correct one to fix the errors
> fix build issue

- MediaBrowser.Controller/Providers/MetadataResult.cs
- MediaBrowser.Providers/Manager/MetadataService.cs
- MediaBrowser.Providers/Omdb/OmdbItemProvider.cs
- MediaBrowser.Providers/TV/Omdb/OmdbEpisodeProvider.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbEpisodeProvider.cs
- MediaBrowser.Providers/TV/TheMovieDb/MovieDbSeriesProvider.cs
- MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs
- MediaBrowser.Providers/TV/TheTVDB/TvdbSeriesProvider.cs
Added ResultLanguage to MetadataResult in order to prioritize metadata merging by matching language
> Prioritize metadata merging by preferred language

- MediaBrowser.Server.Implementations/Session/SessionManager.cs
- MediaBrowser.Server.Startup.Common/ApplicationHost.cs
- MediaBrowser.sln
Prep work for Multi auth providers.
Also prep for future move to change persistence is implemented.
> Manage repositories only through their managers

- Emby.Server.Implementations/Networking/NetworkManager.cs
test available ip4 host address against the endpoint (only local addresses, 10 127 192.68 169), if there's a preliminary match, it finds the subnet of the host ip (255.255.255.0) and makes sure's there's a match between host (255.255.255) and endpoint.
In hindsight, this probably goes beyond the initial request?
> Test for matching subnet of IP's (VPN request)
